"""Author executable DEBUG snippets; validate fixed and buggy code offline before seeding."""
import json
import subprocess
import tempfile
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor
import arrays_bank
from common import BANK, JAVA_SUPPORT

# One intentional logic bug in each related algorithm; the surrounding IO stays read-only.
EDITS = {
 'maximum-subarray-sum': ('best=cur', 'best=0'),
 'products-excluding-self': ('long p=1', 'long p=0'),
 'rotate-array-right': ('(i+k%n)%n', 'i'),
 'count-array-inversions': ('int j=p-1', 'int j=p'),
 'strict-majority': ('c>n/2', 'c>=n/2'),
 'first-missing-positive': ('(n+1)', 'n'),
 'count-target-pairs': ('k-x', 'k+x'),
 'distinct-zero-sum-triplets': ('long ans=0', 'long ans=1'),
 'leftmost-balance-index': ('right-=a[i]', 'right+=a[i]'),
 'maximum-product-subarray': ('Math.max(p,q)', 'p'),
 'shortest-target-sum-window': ('while(s>=k)', 'while(s>k)'),
 'longest-consecutive-values': ('y-x', 'y-x+1'),
 'next-greater-value': ('s.peek()<=a[i]', 's.peek()<a[i]'),
 'warmer-day-distance': ('b[j]=i-j', 'b[j]=a[i]-a[j]'),
 'single-stock-trade': ('(long)x-low', '(long)low-x'),
 'unlimited-stock-trades': ('Math.max(0,a[i]-a[i-1])', '(a[i]-a[i-1])'),
 'maximum-sortable-chunks': ('if(m.isEmpty())', 'if(a[i]==b[i])'),
 'shortest-unsorted-segment': ('r-l+1', 'r-l'),
 'shortest-degree-segment': ('Math.min(best,len)', 'Math.max(best,len)'),
 'nearby-equal-values': ('i-p<=k', 'i-p<k'),
}

def format_body(body):
    # These authored fragments have no string literals containing braces or semicolons.
    return body.replace(';', ';\n').replace('{', '{\n').replace('}', '}\n') + '\n'

def validate(row):
    with tempfile.TemporaryDirectory(prefix='challenge-debug-') as folder:
        path = Path(folder)
        failures = 0
        for version in ('fixed', 'starter'):
            code = row['config']['prefix'] + row[version] + row['config']['suffix']
            (path/'Main.java').write_text(code, encoding='utf-8')
            subprocess.run(['javac','--release','11','Main.java'],cwd=path,check=True,capture_output=True,timeout=30)
            for case in row['tests']:
                result = subprocess.run(['java','-cp',str(path),'Main'],input=case['stdin'],text=True,capture_output=True,timeout=5)
                passed = result.returncode == 0 and result.stdout.strip() == case['expectedOutput'].strip()
                if version == 'fixed':
                    assert passed, (row['slug'],case,result.stderr)
                else:
                    failures += not passed
        return failures

def build():
    prefix, suffix = JAVA_SUPPORT.split('%BODY%')
    rows=[]
    for q in BANK:
        if q['slug'] not in EDITS: continue
        good,bad=EDITS[q['slug']]
        assert q['body'].count(good)==1, q['slug']
        context='// Fix the logic bug. '+q['prompt'].split('\n')[0]+'\n'
        fixed=context+format_body(q['body'])
        starter=context+format_body(q['body'].replace(good,bad,1))
        rows.append(dict(slug=q['slug'],fixed=fixed,starter=starter,
            config=dict(starterCode=starter,prefix=prefix,suffix=suffix,languageId=62),
            tests=[dict(stdin=i,expectedOutput=o) for i,o in q['tests']]))
        if q['slug']=='strict-majority': rows[-1]['tests'][-1]=dict(stdin='2\n1 2\n',expectedOutput='NONE')
        if q['slug']=='nearby-equal-values': rows[-1]['tests'][-1]=dict(stdin='2 1\n9 9\n',expectedOutput='true')
        if q['slug']=='first-missing-positive': rows[-1]['tests'][-1]=dict(stdin='3\n1 2 3\n',expectedOutput='4')
    assert len(rows)==20
    with ThreadPoolExecutor(max_workers=4) as pool:
        failures=list(pool.map(validate,rows))
    assert all(failures), ('Undetected bugs', [r['slug'] for r,f in zip(rows,failures) if not f])
    data=json.dumps([dict(slug=r['slug'],config=r['config'],tests=r['tests'],expected=[r['fixed']]) for r in rows],separators=(',',':'))
    sql='''-- Generated by build_debug_followups.py after Java 11 validation.
-- Requires migrations 12 and 13. Never changes issued snapshots or coding questions.
BEGIN;
DO $$ BEGIN IF current_database()<>'challenge_platform' THEN RAISE EXCEPTION 'Wrong database'; END IF; END $$;
ALTER TABLE challenge_platform.question_followup ADD COLUMN IF NOT EXISTS debug_config jsonb;
ALTER TABLE challenge_platform.question_followup ADD COLUMN IF NOT EXISTS debug_tests jsonb;
ALTER TABLE challenge_platform.session_followup ADD COLUMN IF NOT EXISTS debug_config jsonb;
ALTER TABLE challenge_platform.session_followup ADD COLUMN IF NOT EXISTS debug_tests jsonb;
ALTER TABLE challenge_platform.session_followup ADD COLUMN IF NOT EXISTS debug_source text;
ALTER TABLE challenge_platform.session_followup ADD COLUMN IF NOT EXISTS debug_result jsonb;
ALTER TABLE challenge_platform.session_followup ADD COLUMN IF NOT EXISTS grading_retries integer NOT NULL DEFAULT 0;
ALTER TABLE challenge_platform.session_followup ADD COLUMN IF NOT EXISTS grading_next_at timestamptz;
DO $$ DECLARE c record; BEGIN
 FOR c IN SELECT conname FROM pg_constraint WHERE conrelid='challenge_platform.session_followup'::regclass AND contype='c'
 AND pg_get_constraintdef(oid) LIKE '%review_status%' LOOP
 EXECUTE format('ALTER TABLE challenge_platform.session_followup DROP CONSTRAINT %I',c.conname);
 END LOOP;
END $$;
ALTER TABLE challenge_platform.session_followup ADD CONSTRAINT session_followup_review_status_check
 CHECK(review_status IN ('UNANSWERED','CORRECT','INCORRECT','NEEDS_REVIEW','QUEUED','GRADING_UNAVAILABLE'));
CREATE INDEX IF NOT EXISTS session_followup_debug_queue ON challenge_platform.session_followup(id) WHERE review_status='QUEUED';
CREATE TEMP TABLE debug_seed ON COMMIT DROP AS
SELECT * FROM jsonb_to_recordset($debug$'''+data+'''$debug$::jsonb) AS x(slug text,config jsonb,tests jsonb,expected jsonb);
DO $$ BEGIN
 IF (SELECT count(*) FROM debug_seed s JOIN challenge_platform.question q USING(slug)
 JOIN challenge_platform.question_followup f ON f.question_id=q.id AND f.ordinal=4 AND f.kind='DEBUG')<>20 THEN
 RAISE EXCEPTION 'Expected twenty existing DEBUG follow-ups'; END IF;
END $$;
UPDATE challenge_platform.question_followup f SET debug_config=s.config,debug_tests=s.tests,expected_answer=s.expected,
 rubric='Correct the snippet logic. The wrapped program must pass all ten test cases; equivalent working corrections are accepted.'
FROM debug_seed s JOIN challenge_platform.question q USING(slug) WHERE f.question_id=q.id AND f.ordinal=4 AND f.kind='DEBUG';
COMMIT;
'''
    (Path(__file__).resolve().parent.parent/'14_executable_debug_followups.sql').write_text(sql,encoding='utf-8',newline='\n')
    print(f'Validated 20 snippets: 200 corrected cases passed; {sum(failures)} buggy cases rejected. Generated migration 14; no database changes.')

if __name__=='__main__': build()
