"""Validate locally and generate additive migration 11. Never contacts Judge or a DB."""
import argparse
import concurrent.futures
import hashlib
import importlib
import json
import pathlib
import subprocess
import sys
import tempfile
import time

sys.dont_write_bytecode = True
from common import BANK, STARTER, source

MODULES = ['arrays_bank', 'strings_bank', 'dp_bank', 'graphs_bank', 'grids_bank', 'numbers_bank', 'advanced_bank']
BASE_SLUGS = sorted('coin-change container-with-most-water course-schedule decode-ways edit-distance jump-game kth-largest-element largest-rectangle-histogram longest-increasing-subsequence longest-palindromic-substring maximum-circular-subarray median-two-sorted-arrays merge-intervals minimum-window-substring number-of-islands search-rotated-sorted-array sliding-window-maximum subarray-sum-equals-k trapping-rain-water word-break'.split())
ROOT = pathlib.Path(__file__).resolve().parent

def load():
    for module in MODULES:
        importlib.import_module(module)
    assert len(BANK) == 180, len(BANK)
    assert len({q['slug'] for q in BANK}) == len(BANK)
    assert len({q['title'] for q in BANK}) == len(BANK)
    assert not set(BASE_SLUGS) & {q['slug'] for q in BANK}
    for q in BANK:
        assert 1 <= q['difficulty'] <= 10
        assert len(q['slug']) <= 80 and len(q['title']) <= 200
        assert len(q['tests']) == 10
    return BANK

def compile_java(folder, body):
    src = folder / 'Main.java'
    src.write_text(body, encoding='utf-8')
    result = subprocess.run(['javac', '--release', '11', '-encoding', 'UTF-8', '-d', str(folder), str(src)],
                            capture_output=True, text=True, timeout=60)
    if result.returncode:
        raise RuntimeError(result.stderr)

def validate(q, root):
    folder = root / q['slug']
    folder.mkdir()
    compile_java(folder, source(q['body']))
    for ordinal, (stdin, expected) in enumerate(q['tests'], 1):
        result = subprocess.run(['java', '-Xmx128m', '-cp', str(folder), 'Main'],
                                input=stdin, capture_output=True, text=True, timeout=10)
        if result.returncode or result.stdout.split() != expected.split():
            raise RuntimeError(f"{q['slug']} case {ordinal}: expected {expected!r}, actual {result.stdout!r}, stderr {result.stderr}")
    return q['slug']

SQL_PREFIX = '''-- Generated by db/bank200/build_bank.py after local Java/Python differential validation.
-- Adds 180 Java questions. Existing 20 questions, testcase IDs and candidate history are untouched.
-- Apply only to the challenge_platform database as its owner. Safe reruns verify exact content.
BEGIN;
SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '120s';
DO $guard$ BEGIN
  IF current_database() <> 'challenge_platform' THEN RAISE EXCEPTION 'Wrong database'; END IF;
END $guard$;
SELECT pg_advisory_xact_lock(200, 11);
CREATE TEMP TABLE bank200_question ON COMMIT DROP AS
SELECT * FROM jsonb_to_recordset($bank200$%PAYLOAD%$bank200$::jsonb) AS q(
  slug text, title text, prompt text, difficulty integer, starter_code text,
  reference_solution text, cases jsonb
);
DO $guard$ BEGIN
  IF (SELECT count(*) FROM bank200_question) <> 180 THEN RAISE EXCEPTION 'Expected 180 additions'; END IF;
  IF (SELECT array_agg(slug::text ORDER BY slug) FROM challenge_platform.question
      WHERE is_active AND slug NOT IN (SELECT slug FROM bank200_question))
      IS DISTINCT FROM ARRAY[%BASE%]::text[] THEN
    RAISE EXCEPTION 'Active baseline differs from the expected original 20 questions; review before applying';
  END IF;
END $guard$;
INSERT INTO challenge_platform.question
  (slug,title,prompt,difficulty,language,judge_language_id,starter_code,reference_solution,time_limit_seconds,max_score,is_active)
SELECT slug,title,prompt,difficulty,'Java',62,starter_code,reference_solution,600,100,false
FROM bank200_question ORDER BY slug
ON CONFLICT (slug) DO NOTHING;
DO $guard$ BEGIN
  IF EXISTS (SELECT 1 FROM bank200_question b JOIN challenge_platform.question q USING(slug)
    WHERE (q.title,q.prompt,q.difficulty,q.language,q.judge_language_id,q.starter_code,q.reference_solution,q.time_limit_seconds,q.max_score)
      IS DISTINCT FROM (b.title,b.prompt,b.difficulty,'Java',62,b.starter_code,b.reference_solution,600,100::numeric)) THEN
    RAISE EXCEPTION 'A new-bank slug already exists with different content; no existing question was overwritten';
  END IF;
END $guard$;
CREATE TEMP TABLE bank200_case ON COMMIT DROP AS
SELECT q.id AS question_id, c.ordinal, c.stdin, c.expected_output, c.is_sample
FROM bank200_question b JOIN challenge_platform.question q USING(slug)
CROSS JOIN LATERAL jsonb_to_recordset(b.cases) AS c(ordinal integer, stdin text, expected_output text, is_sample boolean);
INSERT INTO challenge_platform.question_testcase (question_id,ordinal,stdin,expected_output,is_sample,points)
SELECT question_id,ordinal,stdin,expected_output,is_sample,10 FROM bank200_case ORDER BY question_id,ordinal
ON CONFLICT (question_id,ordinal) DO NOTHING;
DO $guard$ BEGIN
  IF EXISTS (SELECT 1 FROM bank200_case b JOIN challenge_platform.question_testcase c USING(question_id,ordinal)
    WHERE (c.stdin,c.expected_output,c.is_sample,c.points) IS DISTINCT FROM (b.stdin,b.expected_output,b.is_sample,10::numeric))
    OR (SELECT count(*) FROM challenge_platform.question_testcase WHERE question_id IN (SELECT question_id FROM bank200_case)) <> 1800 THEN
    RAISE EXCEPTION 'Testcase content/count differs; no existing testcase was overwritten';
  END IF;
END $guard$;
UPDATE challenge_platform.question SET is_active=true
WHERE slug IN (SELECT slug FROM bank200_question) AND NOT is_active;
DO $guard$ BEGIN
  IF (SELECT count(*) FROM challenge_platform.question WHERE is_active) <> 200 THEN RAISE EXCEPTION 'Expected 200 active questions'; END IF;
  IF EXISTS (SELECT 1 FROM challenge_platform.question q
    LEFT JOIN challenge_platform.question_testcase c ON c.question_id=q.id
    WHERE q.is_active GROUP BY q.id HAVING count(c.id)<>10 OR count(c.id) FILTER(WHERE c.is_sample)<>2 OR sum(c.points)<>100) THEN
    RAISE EXCEPTION 'Every active question must have ten testcases, two samples, and 100 total points';
  END IF;
END $guard$;
COMMIT;
'''

def migration(bank):
    payload = [dict(slug=q['slug'],title=q['title'],prompt=q['prompt'],difficulty=q['difficulty'],
                    starter_code=STARTER,reference_solution=source(q['body']),
                    cases=[dict(ordinal=i,stdin=stdin,expected_output=out,is_sample=i<=2)
                           for i,(stdin,out) in enumerate(q['tests'],1)]) for q in sorted(bank,key=lambda q:q['slug'])]
    data=json.dumps(payload, ensure_ascii=True, separators=(',', ':'))
    assert '$bank200$' not in data
    return SQL_PREFIX.replace('%PAYLOAD%',data).replace('%BASE%',','.join("'"+s+"'" for s in BASE_SLUGS))

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--workers',type=int,default=4)
    parser.add_argument('--check',action='store_true',help='Validate without regenerating migration/manifest')
    args=parser.parse_args()
    if not 1 <= args.workers <= 8: parser.error('workers must be 1..8')
    started=time.monotonic()
    bank=load()
    print(f'Loaded {len(bank)} distinct additions; validating {len(bank)*10} cases locally.',flush=True)
    with tempfile.TemporaryDirectory(prefix='challenge_bank200_') as tmp:
        root=pathlib.Path(tmp)
        starter=root/'starter';starter.mkdir();compile_java(starter,STARTER)
        with concurrent.futures.ThreadPoolExecutor(max_workers=args.workers) as pool:
            futures={pool.submit(validate,q,root):q['slug'] for q in bank}
            for count,future in enumerate(concurrent.futures.as_completed(futures),1):
                try: slug=future.result()
                except Exception:
                    for f in futures: f.cancel()
                    raise
                if count%10==0 or count==len(bank):print(f'Validated {count}/{len(bank)}: {slug}',flush=True)
    sql=migration(bank)
    manifest=dict(additional_questions=180,total_questions=200,validated_cases=1800,
                  original_questions_unchanged=BASE_SLUGS,java_release=11,
                  oracle='Independent Python implementations compared with Java stdout tokens',
                  migration_sha256=hashlib.sha256(sql.encode()).hexdigest(),
                  questions=[dict(slug=q['slug'],title=q['title'],difficulty=q['difficulty'],cases=10,samples=2) for q in bank])
    if not args.check:
        (ROOT.parent/'11_expand_question_bank_to_200.sql').write_text(sql,encoding='utf-8',newline='\n')
        (ROOT/'validation.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8',newline='\n')
    print(f'PASS: {len(bank)} solutions, 1800 cases and shared starter; elapsed {time.monotonic()-started:.1f}s.',flush=True)

if __name__=='__main__':main()
