-- Run as the database owner, once per environment. Contains no seeded credentials.
BEGIN;
CREATE SCHEMA IF NOT EXISTS challenge_platform_admin;
REVOKE ALL ON SCHEMA challenge_platform_admin FROM PUBLIC;

CREATE TABLE IF NOT EXISTS challenge_platform_admin.admin_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE CHECK (email = lower(trim(email))),
    password_hash VARCHAR(100) NOT NULL CHECK (password_hash LIKE '$2%'),
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS challenge_platform_admin.daily_limit_reset_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_email VARCHAR(255) NOT NULL REFERENCES challenge_platform_admin.admin_user(email),
    reset_date DATE NOT NULL,
    candidate_id BIGINT NOT NULL,
    locks_removed INTEGER NOT NULL CHECK (locks_removed >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Runtime can authenticate and append audit entries, but cannot create/modify admins
-- or erase the audit history. No CREATE permission on this schema is granted.
GRANT USAGE ON SCHEMA challenge_platform_admin TO challenge_app;
GRANT SELECT ON challenge_platform_admin.admin_user TO challenge_app;
GRANT INSERT ON challenge_platform_admin.daily_limit_reset_audit TO challenge_app;
GRANT USAGE ON SEQUENCE challenge_platform_admin.daily_limit_reset_audit_id_seq TO challenge_app;
COMMIT;
