-- Additive migration. Run as challenge_platform owner before deploying the session backend.
BEGIN;
DO $$ BEGIN
  IF current_database() <> 'challenge_platform' THEN RAISE EXCEPTION 'Wrong database'; END IF;
END $$;
CREATE TABLE IF NOT EXISTS challenge_platform.challenge_session (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash VARCHAR(64) NOT NULL UNIQUE,
  candidate_id BIGINT NOT NULL REFERENCES challenge_platform.candidate(id),
  session_date DATE NOT NULL,
  started_at TIMESTAMPTZ NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  finished_at TIMESTAMPTZ,
  finish_reason VARCHAR(30),
  ip_address VARCHAR(45),
  user_agent TEXT,
  CHECK (expires_at = started_at + interval '10 minutes')
);
CREATE INDEX IF NOT EXISTS challenge_session_expiry ON challenge_platform.challenge_session(expires_at) WHERE finished_at IS NULL;
CREATE TABLE IF NOT EXISTS challenge_platform.session_question (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES challenge_platform.challenge_session(id) ON DELETE CASCADE,
  question_id BIGINT NOT NULL REFERENCES challenge_platform.question(id),
  ordinal INTEGER NOT NULL CHECK (ordinal > 0),
  issued_at TIMESTAMPTZ NOT NULL,
  draft_code TEXT,
  draft_activity TEXT,
  draft_received_at TIMESTAMPTZ,
  draft_revision INTEGER NOT NULL DEFAULT 0,
  attempt_id BIGINT UNIQUE REFERENCES challenge_platform.attempt(id),
  UNIQUE(session_id, question_id),
  UNIQUE(session_id, ordinal),
  CHECK (draft_code IS NULL OR length(draft_code) <= 100000)
);
ALTER TABLE challenge_platform.attempt ADD COLUMN IF NOT EXISTS challenge_session_id BIGINT REFERENCES challenge_platform.challenge_session(id);
ALTER TABLE challenge_platform.attempt ADD COLUMN IF NOT EXISTS session_elapsed_ms BIGINT;
ALTER TABLE challenge_platform.attempt ADD COLUMN IF NOT EXISTS grading_retries INTEGER NOT NULL DEFAULT 0;
ALTER TABLE challenge_platform.attempt ADD COLUMN IF NOT EXISTS grading_next_at TIMESTAMPTZ;
CREATE INDEX IF NOT EXISTS attempt_grading_queue ON challenge_platform.attempt(id) WHERE judge_status = 'QUEUED';
ALTER TABLE challenge_platform.daily_attempt_lock ALTER COLUMN attempt_id DROP NOT NULL;
ALTER TABLE challenge_platform.daily_attempt_lock ADD COLUMN IF NOT EXISTS challenge_session_id BIGINT REFERENCES challenge_platform.challenge_session(id);
ALTER TABLE challenge_platform.activity_session DROP CONSTRAINT IF EXISTS activity_session_attempt_id_key;
ALTER TABLE challenge_platform.activity_session ADD COLUMN IF NOT EXISTS session_question_id BIGINT REFERENCES challenge_platform.session_question(id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS activity_session_question_idx ON challenge_platform.activity_session(session_question_id);
GRANT SELECT, INSERT, UPDATE, DELETE ON challenge_platform.challenge_session, challenge_platform.session_question TO challenge_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA challenge_platform TO challenge_app;
COMMIT;
