-- Additive. Existing questions and attempts are never removed or deactivated.
BEGIN;
DO $$ BEGIN
 IF current_database()<>'challenge_platform' THEN RAISE EXCEPTION 'Wrong database'; END IF;
END $$;
ALTER TABLE challenge_platform.challenge_session ADD COLUMN IF NOT EXISTS flow_version integer NOT NULL DEFAULT 1;
CREATE TABLE IF NOT EXISTS challenge_platform.question_followup (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 question_id bigint NOT NULL REFERENCES challenge_platform.question(id),
 ordinal integer NOT NULL CHECK(ordinal BETWEEN 1 AND 5),
 kind varchar(20) NOT NULL CHECK(kind IN ('FIB','MCQ','DRAG_DROP','DEBUG','SHORT_ANSWER')),
 prompt text NOT NULL CHECK(btrim(prompt)<>''),
 options jsonb NOT NULL DEFAULT '[]' CHECK(jsonb_typeof(options)='array'),
 expected_answer jsonb NOT NULL CHECK(jsonb_typeof(expected_answer)='array'),
 rubric text NOT NULL,
 enabled boolean NOT NULL DEFAULT true,
 UNIQUE(question_id,ordinal)
);
CREATE OR REPLACE VIEW challenge_platform.followup_eligible_question AS
 SELECT q.id FROM challenge_platform.question q
 JOIN challenge_platform.question_followup f ON f.question_id=q.id AND f.enabled
 WHERE q.is_active GROUP BY q.id HAVING count(*)=5;
-- Snapshot the issued set so later authoring cannot change an in-progress or historical attempt.
CREATE TABLE IF NOT EXISTS challenge_platform.session_followup (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 session_question_id bigint NOT NULL REFERENCES challenge_platform.session_question(id) ON DELETE CASCADE,
 followup_id bigint NOT NULL REFERENCES challenge_platform.question_followup(id),
 ordinal integer NOT NULL CHECK(ordinal BETWEEN 1 AND 5),
 kind varchar(20) NOT NULL,
 prompt text NOT NULL,
 options jsonb NOT NULL,
 expected_answer jsonb NOT NULL,
 rubric text NOT NULL,
 answer jsonb,
 submitted_at timestamptz,
 review_status varchar(20) NOT NULL DEFAULT 'UNANSWERED',
 UNIQUE(session_question_id,ordinal),
 CHECK((answer IS NULL)=(submitted_at IS NULL)),
 CHECK(review_status IN ('UNANSWERED','CORRECT','INCORRECT','NEEDS_REVIEW'))
);
GRANT SELECT ON challenge_platform.question_followup,challenge_platform.followup_eligible_question TO challenge_app;
GRANT SELECT,INSERT,UPDATE,DELETE ON challenge_platform.session_followup TO challenge_app;
GRANT USAGE,SELECT ON SEQUENCE challenge_platform.session_followup_id_seq TO challenge_app;
REVOKE INSERT,UPDATE,DELETE ON challenge_platform.question_followup FROM challenge_app;
COMMIT;
